export const Ids = {
    app: "app",
    titlebar: "titlebar",
    fileInput: "file-input",
    sidebar: "sidebar",
    sidebarHeader: "sidebar-header",
    tagList: "tag-list",
    allItem: "all-item",
    allCount: "all-count",
    main: "main",
    toolbar: "toolbar",
    search: "search",
    count: "count",
    grid: "grid",
    dropOverlay: "drop-overlay",

    modalBg: "modal-bg",
    modal: "modal",
    modalHeader: "modal-header",
    modalFilename: "modal-filename",
    modalClose: "modal-close",
    modalPreviewWrap: "modal-preview-wrap",
    modalPreview: "modal-preview",
    modalBody: "modal-body",
    modalTagInputRow: "modal-tag-input-row",
    modalTagInput: "modal-tag-input",
    modalTagAddBtn: "modal-tag-add-btn",
    modalTagList: "modal-tag-list",
    modalBtnCancel: "modal-btn-cancel",
    modalBtnSave: "modal-btn-save",
} as const;
